config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'books#index'
  resources :requests, only: %i[index create]
  resources :authors, only: [:create]
  resources :books, only: %i[index show new create] do
    resources :comments, only: [:create]
  end
end

app/models/admin_user.rb
# Admin User Model
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
# Application Record Model
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
# Author Model
class Author < ApplicationRecord
  validates :name, presence: true
  has_many :books, dependent: :destroy
end

app/models/average_cache.rb
# Rating Average Cache Model
class AverageCache < ActiveRecord::Base
  belongs_to :rater, class_name: 'User'
  belongs_to :rateable, polymorphic: true
end

app/models/book.rb
# Book Model
class Book < ApplicationRecord
  has_many :requests
  has_many :comments
  belongs_to :author
  mount_uploader :image, BookImageUploader
  ratyrate_rateable 'general'
  validates :title, :description, :image, :author, presence: true
  validates :year, presence: true, numericality: true
  validate :year_margins

  def year_margins
    return false if year.nil?
    return false unless year.between? 1700, Time.current.year
    errors.add(:year, 'year must be between 1700 and ' +
      Time.current.year.to_s)
  end
end

app/models/comment.rb
# Comment Controller
class Comment < ApplicationRecord
  validates :description, presence: true
  belongs_to :book
  belongs_to :user
end

app/models/overall_average.rb
# Rating Overall Average Model
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, polymorphic: true
end

app/models/rate.rb
# Rate Model
class Rate < ActiveRecord::Base
  belongs_to :rater, class_name: 'User'
  belongs_to :rateable, polymorphic: true
end

app/models/rating_cache.rb
# Rating Cache Model
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, polymorphic: true
end

app/models/request.rb
# Request Model
class Request < ApplicationRecord
  enum status: %i[pending denied approved]
  belongs_to :book
  belongs_to :user
  validates :book, :user, :status, presence: true
end

app/models/user.rb
# User Model
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :requests
  has_many :books, through: :requests
  ratyrate_rater

  def requested?(book)
    books.include? book
  end

  def request_status(book)
    requests.where(book_id: book.id).pluck(:status).first.titleize
  end
end

app/controllers/application_controller.rb
# Aplication Controller
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def after_sign_out_path_for(_)
    new_user_session_path
  end
end

app/controllers/authors_controller.rb
# Authors controller
class AuthorsController < ApplicationController
  def index
    respond_to do |format|
      format.html
      format.json { render json: { data: Author.all }, status: :ok }
    end
  end

  def create
    Author.create(book_params)
  end

  private

  def book_params
    params.require(:author).permit(:name)
  end
end

app/controllers/books_controller.rb
# Books Controller
class BooksController < ApplicationController
  helper_method :book
  before_action :authenticate_user!

  def index
    @books = Book.all
    respond_to do |format|
      format.html
      format.json { render json: { data: @books }, status: :ok }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: { data: book }, status: :ok }
    end
  end

  def new
    @authors = Author.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book
    else
      flash.now[:error] = @book.errors
      @authors = Author.all
      render :new
    end
  end

  def book
    @book ||= Book.find(params[:id])
  end

  private

  def book_params
    params.require(:book).permit(
      :title,
      :author_id,
      :description,
      :year,
      :image
    )
  end
end

app/controllers/comments_controller.rb
# Comments Controller
class CommentsController < ApplicationController
  helper_method :book

  def create
    @comment = book.comments.create(comment_params.merge(
                                      user_id: current_user.id
    ))
  end

  def book
    @book ||= Book.find(params[:book_id])
  end

  def comment_params
    params.require(:comment).permit(:description)
  end
end

app/controllers/rater_controller.rb
# Rater Controller
class RaterController < ApplicationController
  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]
      render json: true
    else
      render json: false
    end
  end
end

app/controllers/registrations_controller.rb
# Registrations Controller
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/controllers/requests_controller.rb
# Requests Controller
class RequestsController < ApplicationController
  before_action :authenticate_user!

  def index
    @requests = current_user.requests
  end

  def create
    @book = Book.find(params[:book_id])
    @request = @book.requests.create(user: current_user)
  end
end

app/helpers/application_helper.rb
# Application Helper
module ApplicationHelper
end

app/views/authors/new.html.erb
<%= form_for :author, url: authors_path do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %> <br>

  <%= f.submit %>
<% end %>

app/views/books/index.html.erb
<div class="home-container">
  <div class="title">
    <h1> Books on the library </h1>
  </div>
  <table class="books-table">
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to book.title, book %></td>
        <td class="opacity dark-opacity"><%= book.author.name %></td>
        <td class="opacity dark-opacity"><%= book.year %></td>
        <% if user_signed_in? %>
          <% if !current_user.requested?(book) %>
            <td id='<%= book.id %>'>
              <%= link_to 'Request', requests_path(book_id: book.id), method: :post, remote: true, class: "bold underlined" %>
            </td>
          <% else %>
            <td class="<% if current_user.request_status(book) == "denied"%>denied bold<% else %>bold light-opacity <% end %>"><%= current_user.request_status(book) %></td>  
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </table>
</div>

app/views/books/new.html.erb
<%= form_for @book, url: books_path do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %> <br>
  <%= f.label :author %>
  <%= f.collection_select(:author_id, @authors, :id, :name) %> <br>
  <%= f.label :year %>
  <%= f.number_field :year %> <br>
  <%= f.label :description %>
  <%= f.text_field :description %> <br>
  <%= f.label :image %>
  <%= f.file_field :image %> <br>

  <%= f.submit %>
<% end %>

app/views/books/show.html.erb
<div class="comments-wrapper">
  <div class="book-container">
    <div class="image"><%= image_tag(book.image_url) %></div>
    <div class="side-book-information">
      <div class="book-title"><%= book.title %></div>
      <div class="book-author"><%= book.author.name %></div>
      <br>
      <div class="book-year-request">
        <h4><%= book.year %></h4> 
        <% if !current_user.requested?(book) %>
          <span id='<%= book.id %>'>
            <%= link_to 'Request', requests_path(book_id: book.id), method: :post, remote: true, class: "request" %>
          </span>
        <% else %>
          <span class='bold big-20  <%= current_user.request_status(book) == "denied" ? "denied" : "dark-opacity" %>'><%= current_user.request_status(book) %></span>  
        <% end %>
      </div>
      <p><%= book.description %></p>
    </div>
  </div>
  <div class='comments-container'>
    <h3>Comments</h3>
      <% book.comments.each do |comment|%>
        <div class="comment">
          <h4><%= comment.user.name %> - </h5>
          <%= rating_for_user book, comment.user, 'general', star_on: '/assets/fill_star.png', star_off: '/assets/empty_star.png', disable_after_rate: true %>
          <br><br>
          <%= comment.description %>
        </div>
        <div class="line-separator"></div>
      <% end %>
    <div id="add-comment"></div>
    <div class="new-comment">
      <%= form_for :comment, url: book_comments_path(book), remote: true do |f| %>
          <h4>Add a comment - Rate:</h4>
          <%= rating_for book, "general", star_on: '/assets/fill_star.png', star_off: '/assets/empty_star.png', cancel: true %>
          <%= f.text_area :description, placeholder:"Comment", class:'text_area' %> <br>
          <%= f.submit "Comment", class:"button" %>
      <% end %>
    </div>
  </div>
</div>
<br><br><br>

app/views/comments/create.js.erb
$('#add-comment').append('<div class="comment"><h4><%= @comment.user.name %></h4><%= rating_for_user book, @comment.user, "general", star_on: "/assets/fill_star.png", star_off: "/assets/empty_star.png", disable_after_rate: true %>  <br><%= @comment.description %></div><div class="line-separator"></div>');
$('#comment_description').val("");

app/views/layouts/_errors.html.erb
<div class="errors">
  <ul>
    <% flash[:error].each do |key, value| %>
      <% if value != [] && !value.nil? %>
        <li>
          <%= key.to_s.capitalize + " " + value.to_s %>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/layouts/_header.html.erb
<ul class="header-container">
  <li class="main"><%= link_to 'The library', books_path,  class: "main-tab " %></li>
  <li><%= link_to 'My Books', requests_path, class: "second-tab active" %></li>
  <li><%= link_to 'LOG OUT', destroy_user_session_path, method: :delete, class: "second-tab" %></li>
</ul>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectLibrary</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/header.html.erb' %>
    <% if flash.any? && flash[:error].present?  %>
      <%= render partial: 'layouts/errors.html.erb' %>
    <% end -%>
    <%= yield %>
  </body>
</html>

app/views/requests/create.js.erb
$('#<%= @book.id %>').html('<%= @request.status.titleize %>');
$('#<%= @book.id %>').addClass("bold big-20 dark-opacity");

app/views/requests/index.html.erb
<div class="title"><h1>Books on my shelf</h1></div>
<div class="my-books">
  <table class="books-table">
    <% @requests.each do |request| %>
    <tr>
      <td class="date"><%= request.created_at.strftime("%d-%m-%Y") %></td>
      <td><%= link_to request.book.title, request.book, class: "bold" %></td>
      <td class="opacity dark-opacity"><%= request.book.author.name %></td>
      <td class="<% if request.status == "denied"%>denied bold<% else %>bold light-opacity <% end %>"><%= request.status.titleize %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/user/Login.html.erb
<h1>User#Login</h1>
<p>Find me in app/views/user/Login.html.erb</p>